// <auto-generated />
using Bootstrapdb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bootstrapdb.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bootstrap1.Models.Catagories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Name");

                    b.Property<int>("Stock");

                    b.HasKey("Id");

                    b.ToTable("Catagorieses");
                });

            modelBuilder.Entity("Bootstrap1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatagoriesId");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<string>("ProductModel");

                    b.Property<string>("Size");

                    b.Property<int>("SubCategoriesId");

                    b.HasKey("Id");

                    b.HasIndex("CatagoriesId");

                    b.HasIndex("SubCategoriesId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Bootstrap1.Models.SubCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriesId");

                    b.Property<string>("Code");

                    b.Property<string>("Image");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("SubName");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.ToTable("SubCategorieses");
                });

            modelBuilder.Entity("Bootstrap1.Models.Product", b =>
                {
                    b.HasOne("Bootstrap1.Models.Catagories", "Catagories")
                        .WithMany("Products")
                        .HasForeignKey("CatagoriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bootstrap1.Models.SubCategories", "SubCategories")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bootstrap1.Models.SubCategories", b =>
                {
                    b.HasOne("Bootstrap1.Models.Catagories", "Catagories")
                        .WithMany("SubCategorieses")
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
